version: "3.9"
services:
  nextapp:
    container_name: nextapp
    image: apps/admin-panel
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: ./
      dockerfile: ./apps/admin-panel/Dockerfile
    ports:
      - 3000:3000
  nestapp:
    container_name: nestapp
    image: apps/server
    volumes:
      - type: bind
        source: .
        target: /app
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3001:3001
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodata:
